// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { appEnv } from '@/env';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(appEnv.supabaseUrl, appEnv.supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
